Dev
allun26/HTML-CSS-Building-with-css-framework pull request #5
Opened 2019-08-01 15:43 UTC by vieiramanda11

2019-08-01 17:39 UTC, Oghenebrume50 commented
Reviewing.......

2019-08-02 07:22 UTC, bolah2009 commented
Currently been reviewed

2019-08-02 08:06 UTC, bolah2009 requested changes
## Nice Job Team :clap: 

The main objective of the project is to ...

> Write the CSS necessary to create a basic 12-column grid framework.

In which you have done a nice job :+1: 

However, to demonstrate it's a **12-column grid framework** I would suggest making the [cloned](https://raw.githack.com/allun26/HTML-CSS-Building-with-css-framework/dev/index.html) page more responsive:

#### Consider using the framework more effectively to achieve this responsiveness. See below:

| Current | Preferred |
| :-----: | :-----: |
| ![css frame responsive current](https://user-images.githubusercontent.com/36057474/62354266-5ad64800-b504-11e9-8531-e7577f40bf8b.gif) | ![css frame responsive preffred](https://user-images.githubusercontent.com/36057474/62354267-5b6ede80-b504-11e9-8161-935a1edbbe0d.gif) |

Good luck with your next submission.

Cheers
[Bola](https://bolabuari.com/)

2019-08-02 08:06 UTC, bolah2009 commented on styles/styles.css
> +    justify-content: center;
`SUGGESTION`

Consider using the framework instead, since this CSS property has been defined there.

2019-08-02 08:16 UTC, bolah2009 commented
I would also suggest using `.gitignore` in the project for files that are not related to the project. Currently, there are **1654** files in this project :open_mouth:. Alternatively, consider using `font-awesome` CDN instead.

2019-08-02 22:47 UTC, samgaco commented
### Hi @vieiramanda11 and @allun26 :hand: 

### Your project is approved, you can merge and submit the completion form :+1:. But before doing so, please, address the following:

* You still have to solve the linters checks that have failed.
* Try using a feature-branch for your next projects, read more about it [here]
(https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/)
* **[OPTIONAL]** The point that @bolah2009 made is still not covered:

> #### Consider using the framework more effectively to achieve this responsiveness. See below:
> Current	Preferred
> ![css frame responsive current](https://user-images.githubusercontent.com/36057474/62354266-5ad64800-b504-11e9-8531-e7577f40bf8b.gif)	![css frame responsive preffred](https://user-images.githubusercontent.com/36057474/62354267-5b6ede80-b504-11e9-8161-935a1edbbe0d.gif)


### Anyways, congratulations on the good work and having your last project completed :clap:

2019-08-05 15:03 UTC, merged